name: Auto update DB
on:
  push:
  schedule:
    - cron: '0 5,13,21 * * *'

jobs:
  run:
    name: Update games DB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Run the update
        run: npm run extract

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: 'chore: updated gog games'
          add: '*.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
